### ISSUE TITLE
bug: editor tests fail in 2020.2 and newer

### ISSUE THREAD

**Issue by uweenukr** [MirageNet/Mirage#778]
**Describe the bug**
Editor tests fail due to ILPostProcessor change in Unity Editor versions 2020.2+. Likely caused by #525

**Comment by Lymdun** [comment]
The issue cause is a bit different than that.
Basically, it is caused by how compilation errors after weaving are detected through the test suite. (see Tests/Weaver/Assembler.cs)
When our test assembly has been compiled, the test suite is getting compiler messages thanks to AssemblyBuilder.buildFinished event, but for some reason it is detecting weaver errors (that are getting tested) since 2020.2+, which breaks the [SetUp] part of tests.
